# Generated by Django 5.2.5 on 2025-08-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('horario', models.CharField(max_length=100)),
                ('cupo_disponible', models.IntegerField()),
                ('docente', models.CharField(max_length=100)),
            ],
        ),
    ]
