# Generated by Django 5.2.5 on 2025-08-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('departamneto', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
            ],
        ),
    ]
