# Generated by Django 5.2.5 on 2025-08-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='departamneto',
            new_name='departamento',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
