# Generated by Django 5.2.5 on 2025-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_rename_departamneto_alumno_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
